services:
  prophetic-front:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        CACHEBUST: ${CACHEBUST:-1}
    container_name: prophetic-front-staging
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Auth environment variables
      - AUTH_SECRET=${AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # Supabase environment variables
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Prophetic API (Perplexity + Claude)
      - PROPHETIC_API_URL=${PROPHETIC_API_URL}
      - PROPHETIC_API_TOKEN=${PROPHETIC_API_TOKEN}
      # Legacy OpenRouter API (no longer used)
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      # Environment-based access control (admin-only for staging/preprod)
      - NEXT_PUBLIC_APP_ENV=staging
      - NEXT_PUBLIC_PRODUCTION_URL=${NEXT_PUBLIC_PRODUCTION_URL}

      - ENVIRONNEMENT=${ENVIRONNEMENT}
      - DEV_MODE=true

    restart: unless-stopped
    networks:
      - prophetic-network

networks:
  prophetic-network:
    driver: bridge
