services:
  prophetic-front:
    image: prophetic/prophetic-front:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SPECIALITY: ${NEXT_PUBLIC_SPECIALITY}
    container_name: prophetic-front
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - prophetic-network

networks:
  prophetic-network:
    external: true