/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/langchain_agent/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query LangChain Agent (SSE Streaming)
         * @description ## Intelligent ReAct Agent for Luxury Collectibles
         *
         *     Query the intelligent ReAct agent that autonomously answers questions about luxury collectibles and investments.
         *     Returns **Server-Sent Events (SSE)** streaming responses.
         *
         *     ### Response Format
         *
         *     The endpoint returns an SSE stream where each event is a JSON object prefixed with `data: `.
         *
         *     ```
         *     data: {"type": "chunk", "content": "Based on my analysis..."}
         *
         *     data: {"type": "marketplace_search_response", "found": true, "artworks": [...]}
         *     ```
         *
         *     ### SSE Event Types
         *
         *     The `type` field determines how to process each event:
         *
         *     | Type | Description | Trigger Examples |
         *     |------|-------------|------------------|
         *     | `chunk` | Regular text content | All responses include text chunks |
         *     | `error` | Error message | When something fails |
         *     | `artist_search_response` | Artist information | "Who is Picasso?", "Tell me about Banksy" |
         *     | `marketplace_search_response` | Available artworks | "Find artworks by Banksy", "Paintings for sale" |
         *     | `real_estate_search_response` | Luxury properties | "Apartments in Paris", "Villas in Provence" |
         *     | `clothes_search_response` | Luxury fashion items | "Hermès Birkin bags", "Chanel bags for women" |
         *     | `insight_search_response` | Market insights | "Wine investment trends", "Watch market predictions" |
         *     | `portfolio_search_response` | Investment portfolios | "I have 50k to invest", "Portfolio recommendations" |
         *     | `product_portfolio_response` | Multi-product portfolios | "Generate 5-product portfolio", "Create multi-category portfolio" |
         *
         *     ### Available Tools
         *
         *     The agent autonomously selects tools based on the question:
         *
         *     1. **artist_search** - Web search for artist information
         *     2. **marketplace_artwork_search** - Search Artsy, Artsper, Saatchi Art for available artworks
         *     3. **search_luxury_real_estate** - Search James Edition for luxury properties (France/US)
         *     4. **clothes_marketplace_search** - Search Farfetch, Rebag, Vestiaire Collective for luxury fashion items
         *     5. **query_insights** - Query market insight documents (wine, watches, cars, etc.)
         *     6. **return_portfolio_information** - Get curated investment portfolios (5K-50M€)
         *     7. **generate_product_portfolio** - Generate multi-product portfolios with deep search (2-10 products)
         *
         *     ### Insight Document Types
         *
         *     Available for `query_insights` tool, organized by category and tier:
         *
         *     - **Categories**: artist, bijoux, cards, cars, montre, property, bag, sneakers, whisky, wine
         *     - **Tiers**: discover (basic), intelligence (intermediate), oracle (advanced)
         *     - **Format**: `{category}_{tier}` (e.g., `wine_intelligence`, `artist_oracle`)
         *
         *     ### Portfolio Ranges
         *
         *     Supported investment amounts for `return_portfolio_information`:
         *
         *     - 5K-10K€, 10K-20K€, 20K-40K€, 40K-80K€, 80K-150K€
         *     - 150K-300K€, 300K-1M€, 1M-5M€, 5M-10M€, 10M-50M€, 50M+€
         */
        post: operations["langchain_agent_query_endpoint_langchain_agent_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/langchain_agent/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Langchain Agent Info Endpoint
         * @description Get information about the LangChain ReAct agent's capabilities and available tools
         */
        get: operations["langchain_agent_info_endpoint_langchain_agent_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/langchain_agent/stream-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Langchain Agent Stream Test Endpoint
         * @description Test endpoint that streams random lorem ipsum text for 5-20 seconds. Simulates the /langchain_agent/query endpoint streaming behavior. Useful for testing client-side SSE handling without consuming LLM credits.
         */
        post: operations["langchain_agent_stream_test_endpoint_langchain_agent_stream_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/clear-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Cache Endpoint
         * @description Clear the files cache. Returns the number of files that were cached.
         */
        post: operations["clear_cache_endpoint_test_clear_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markdown/tiers-independant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tiers-Independent Markdown Content
         * @description ## Get Tiers-Independent Markdown Content
         *
         *     Returns an SSE stream for vignette files, independent of tier level.
         *
         *     Always emits a `markdown` event first (text + questions), then optionally a
         *     `product` event with marketplace results when `need_search` is `true` in the DB.
         *
         *     ### Path Structure
         *
         *     Files are loaded from: `{environment}/VIGNETTES/{filename}.md`
         *
         *     ### SSE Events
         *
         *     1. `{"type": "markdown", "text": "...", "questions": "..."}` — always emitted first
         *     2. `{"type": "status", ...}` — emitted before scraping starts (only when need_search=true)
         *     3. Category-specific product event — emitted after scraping (only when need_search=true)
         *
         *     ### Example
         *
         *     ```
         *     GET /markdown/tiers-independant?markdown_name=overview&category=BIJOUX
         *     ```
         */
        get: operations["get_tiers_independant_markdown_markdown_tiers_independant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markdown/tiers-dependant/without-sub-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tiers-Dependent Markdown Content (No Sub-Category)
         * @description ## Get Tiers-Dependent Markdown Content
         *
         *     Returns markdown content for files organized by tier level and category.
         *
         *     ### Path Structure
         *
         *     Files are loaded from: `{environment}/{tier}/{category}/{filename}.md`
         *
         *     ### Available Tiers
         *
         *     | Tier | Description |
         *     |------|-------------|
         *     | `DISCOVER` | Basic content tier |
         *     | `INTELLIGENCE` | Intermediate content tier |
         *     | `ORACLE` | Premium content tier |
         *
         *     ### Available Categories
         *
         *     | Category | Description |
         *     |----------|-------------|
         *     | `PORTFOLIO` | Portfolio content |
         *     | `CASH_FLOW_LEASING` | Cash flow leasing content |
         *
         *     ### Example
         *
         *     ```
         *     GET /markdown/tiers-dependant/without-sub-category?tiers_level=DISCOVER&category=PORTFOLIO&markdown_name=strategy
         *     ```
         *
         *     This will load: `staging/DISCOVER/PORTFOLIO/strategy.md`
         */
        get: operations["get_tiers_dependant_markdown_without_subcategory_markdown_tiers_dependant_without_sub_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markdown/tiers-dependant/with-sub-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Random Markdown from Sub-Category Folder
         * @description ## Get Random Markdown from Sub-Category Folder
         *
         *     Returns a randomly selected markdown file from a folder organized by tier,
         *     category, and sub-category (flash card type).
         *
         *     ### Path Structure
         *
         *     Files are loaded from: `{environment}/{tier}/{category}/{sub-category}/*.md`
         *     A random file is selected from all available markdown files in that folder.
         *
         *     ### Available Tiers
         *
         *     | Tier | Description |
         *     |------|-------------|
         *     | `DISCOVER` | Basic content tier |
         *     | `INTELLIGENCE` | Intermediate content tier |
         *     | `ORACLE` | Premium content tier |
         *
         *     ### Available Categories
         *
         *     | Category | Description |
         *     |----------|-------------|
         *     | `RANKING` | Ranking content |
         *     | `FLASH_INVEST` | Flash invest content |
         *
         *     ### Available Sub-Categories (Flash Cards)
         *
         *     | Sub-Category | Description |
         *     |--------------|-------------|
         *     | `art` | Contemporary art flash cards |
         *     | `bijoux` | Jewelry flash cards |
         *     | `cards_us` | US trading cards flash cards |
         *     | `cars` | Cars flash cards |
         *     | `immo_luxe` | Luxury real estate flash cards |
         *     | `montres_luxe` | Luxury watches flash cards |
         *     | `sacs` | Bags flash cards |
         *     | `sneakers` | Sneakers flash cards |
         *     | `whisky` | Whisky flash cards |
         *     | `wine` | Wine flash cards |
         *
         *     ### Example
         *
         *     ```
         *     GET /markdown/tiers-dependant/with-sub-category?tiers_level=DISCOVER&category=FLASH_INVEST&sub_category=sneakers
         *     ```
         *
         *     This will return a random markdown file from: `staging/DISCOVER/FLASH_INVEST/sneakers/*.md`
         */
        get: operations["get_tiers_dependant_markdown_with_subcategory_markdown_tiers_dependant_with_sub_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vignettes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vignettes by Category
         * @description ## Get Vignettes by Category
         *
         *     Returns a list of vignettes (brand cards) filtered by category.
         *     Each vignette represents a brand/product with market insights.
         *
         *     ### Available Categories
         *
         *     | Category | Description |
         *     |----------|-------------|
         *     | `ART` | Contemporary art and artists |
         *     | `ART_TRADING_VALUE` | Art trading value |
         *     | `BIJOUX` | Jewelry and precious stones |
         *     | `CARDS_US` | US trading cards and sports cards |
         *     | `CARS` | Collectible and classic cars |
         *     | `CASH_FLOW_LEASING` | Cash flow and leasing options |
         *     | `CLASSIQUES` | Classical art |
         *     | `EMERGENTS` | Emerging artists |
         *     | `FIGURATIF` | Figurative art |
         *     | `IMMO_LUXE` | Luxury real estate |
         *     | `MARCHE_SPOT` | Spot market |
         *     | `MODERNES` | Modern art |
         *     | `MONTRES_LUXE` | Luxury watches |
         *     | `POP_ART` | Pop art |
         *     | `POST-WAR` | Post-war art |
         *     | `SACS` | Luxury bags (Hermès, LV, etc.) |
         *     | `SNEAKERS` | Collectible sneakers |
         *     | `STREET_ART` | Street art |
         *     | `SURREALISME` | Surrealism |
         *     | `WHISKY` | Whisky and spirits |
         *     | `WINE` | Fine wines |
         *
         *     ### Response Fields
         *
         *     Each vignette contains:
         *     - `category`: Category of the vignette
         *     - `brand_name`: Name of the brand/product
         *     - `public_url`: Image URL for display
         *     - `subtitle`: Optional tagline
         *     - `score`: Market score (0-100)
         *     - `trend`: Direction indicator (`up`, `down`, or `same`)
         *     - `category_alias`: Display category name, only used for `MARCHE_SPOT`
         *     - `plan`: Subscription plan this vignette belongs to (`discover`, `intelligence`, `oracle`)
         *
         *     ### Ordering
         *
         *     For `MARCHE_SPOT`, vignettes are ordered by plan: `discover` first, then `intelligence`, then `oracle`.
         */
        get: operations["get_vignettes_vignettes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FlashCard
         * @description Flash card types available for educational content
         *     !if you change structure here, change it also in 'vignettes.py' model ! !
         * @enum {string}
         */
        FlashCard: "ART" | "BIJOUX" | "CARDS_US" | "CARS" | "IMMO_LUXE" | "MONTRES_LUXE" | "SACS" | "SNEAKERS" | "WHISKY" | "WINE";
        /**
         * FlashCardType
         * @description Flash card type available for educational content
         * @enum {string}
         */
        FlashCardType: "flash_invest" | "ranking" | "portfolio";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsightCategory
         * @description Flash card types available for educational content
         *     !if you change structure here, change it also in 'vignettes.py' model ! !
         * @enum {string}
         */
        InsightCategory: "ARTIST" | "BIJOUX" | "CARDS_US" | "CARS" | "REAL_ESTATE" | "MONTRES" | "SACS" | "SNEAKERS" | "WHISKY" | "WINE";
        /**
         * LangChainAgentRequest
         * @description Request model for LangChain ReAct agent query
         */
        LangChainAgentRequest: {
            /**
             * Question
             * @description The question to ask the agent
             * @example What Nike sneakers should I buy?
             * @example I have 50,000 euros to invest in collectibles
             * @example Quels sont les meilleurs vins de Bordeaux?
             * @example Best scotch whisky for beginners?
             * @example How to grade baseball cards?
             */
            question: string;
            /**
             * Model
             * @description The Anthropic model to use for the ReAct agent and tool execution
             * @default claude-sonnet-4-6
             * @example claude-sonnet-4-6
             * @example claude-opus-4-6
             * @example claude-haiku-4-5-20251001
             */
            model: string;
            /**
             * @description The tiers level to use for processing the query
             * @default DISCOVER
             * @example discover
             * @example flash
             * @example intelligence
             * @example oracle
             */
            tiers_level: components["schemas"]["TiersLevel"];
            /**
             * User Id
             * @description Optional user identifier for Langfuse tracking. If not provided, defaults to authenticated username
             * @example user_123
             * @example john.doe@example.com
             */
            user_id?: string | null;
            /**
             * Session Id
             * @description Optional session identifier for Langfuse tracking and grouping related queries
             * @example session_123
             * @example user_chat_abc
             */
            session_id?: string | null;
            /**
             * Conversation History
             * @description Optional conversation history as alternating user/assistant messages. Max 20 messages total (10 user + 10 assistant exchanges), each message max 50000 characters. Format: [{'role': 'user', 'content': '...'}, {'role': 'assistant', 'content': '...'}]
             * @example [
             *       {
             *         "content": "Tell me everything about Pierre Malin",
             *         "role": "user"
             *       },
             *       {
             *         "content": "Pierre Malin is a contemporary artist...",
             *         "role": "assistant"
             *       },
             *       {
             *         "content": "How old is he?",
             *         "role": "user"
             *       }
             *     ]
             * @example [
             *       {
             *         "content": "What are the best sneakers?",
             *         "role": "user"
             *       },
             *       {
             *         "content": "Based on current trends...",
             *         "role": "assistant"
             *       }
             *     ]
             */
            conversation_history?: {
                [key: string]: string;
            }[] | null;
            /**
             * Enable Rephrasing
             * @description Whether to automatically rephrase follow-up questions to include context from conversation history. When enabled, questions like 'now I want on the 8th' are rephrased to 'I want a flat in the 8th arrondissement'. Improves agent understanding of contextual questions.
             * @default true
             * @example true
             * @example false
             */
            enable_rephrasing: boolean;
            /**
             * File Url
             * @description Optional URL of a file stored in Supabase storage bucket. The agent can use this file as additional context for answering the question. Should be a publicly accessible or authenticated URL to a Supabase storage object.
             * @example https://your-project.supabase.co/storage/v1/object/public/bucket-name/file.pdf
             * @example https://your-project.supabase.co/storage/v1/object/authenticated/bucket-name/document.txt
             */
            file_url?: string | null;
            /** @description Option flashcard on specific subject */
            flash_cards?: components["schemas"]["FlashCard"] | null;
            /** @description Optional flash card type for educational content */
            flash_card_type?: components["schemas"]["FlashCardType"] | null;
            /**
             * Uuid Product
             * @description Optional UUID of a specific product in the 'abcdaire' table. When provided, triggers a deep insight search for that product. The tool checks 'deep_insight' column for a cached language-specific insight, falling back to the category template if not found.
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            uuid_product?: string | null;
            /**
             * @description Category of the product identified by uuid_product. Used to select the correct insight template when no cached insight is found. Required when uuid_product is provided.
             * @example WINE
             * @example MONTRES
             * @example SACS
             */
            product_category?: components["schemas"]["InsightCategory"] | null;
            /**
             * Artist Uuid
             * @description Optional UUID of a specific artist row in the 'artists_stats' table. When provided, triggers a deep insight search for that artist. The tool checks 'deep_insight' column for a cached language-specific insight, falling back to the ARTIST category template if not found.
             * @example 550e8400-e29b-41d4-a716-446655440001
             */
            artist_uuid?: string | null;
        };
        /**
         * MarkdownResponse
         * @description Response model for markdown content
         */
        MarkdownResponse: {
            /**
             * Text
             * @description The markdown content of the document
             */
            text: string;
            /**
             * Questions
             * @description Questions associated with the markdown content
             */
            questions?: string | null;
            /**
             * Product
             * @description Marketplace search results for the product, returned when return_product=true
             */
            product?: unknown | null;
        };
        /**
         * Plan
         * @description Subscription tier level (maps to 'plan' column in Supabase)
         * @enum {string}
         */
        Plan: "discover" | "intelligence" | "oracle";
        /**
         * StreamTestRequest
         * @description Request model for streaming text test endpoint
         */
        StreamTestRequest: {
            /**
             * Duration
             * @description Duration in seconds to stream text. If not provided, randomly selects between 5-20 seconds
             * @example 5
             * @example 10
             * @example 15
             * @example 20
             */
            duration?: number | null;
        };
        /**
         * TiersLevel
         * @enum {string}
         */
        TiersLevel: "DISCOVER" | "FLASH" | "INTELLIGENCE" | "ORACLE";
        /**
         * Trend
         * @description Trend indicator for market direction
         * @enum {string}
         */
        Trend: "up" | "down" | "same";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VignetteData
         * @description Individual vignette (brand card) with market insights.
         *
         *     Represents a brand or product within a category, providing
         *     investment signals and market analysis.
         * @example {
         *       "brand_name": "Nike Air Jordan",
         *       "category": "SNEAKERS",
         *       "public_url": "https://storage.example.com/vignettes/jordan.png",
         *       "score": 87,
         *       "subtitle": "Limited Edition Collection",
         *       "trend": "up"
         *     }
         * @example {
         *       "brand_name": "Rolex Submariner",
         *       "category": "MONTRES_LUXE",
         *       "public_url": "https://storage.example.com/vignettes/rolex.png",
         *       "score": 92,
         *       "subtitle": "Vintage Timepiece",
         *       "trend": "up"
         *     }
         * @example {
         *       "brand_name": "Chateau Margaux 2010",
         *       "category": "WINE",
         *       "public_url": "https://storage.example.com/vignettes/margaux.png",
         *       "score": 78,
         *       "subtitle": "Premium Selection",
         *       "trend": "down"
         *     }
         */
        VignetteData: {
            /**
             * @description Category this vignette belongs to
             * @example SNEAKERS
             * @example WINE
             * @example MONTRES_LUXE
             */
            category: components["schemas"]["Vignettes"];
            /**
             * Brand Name
             * @description Brand or product name
             * @example Nike Air Jordan
             * @example Rolex Submariner
             * @example Chateau Margaux 2010
             */
            brand_name: string;
            /**
             * Public Url
             * @description Publicly accessible URL of the vignette image
             * @example https://storage.supabase.co/vignettes/jordan.png
             */
            public_url?: string | null;
            /**
             * Subtitle
             * @description Subtitle or tagline for the vignette
             * @example Limited Edition Collection
             * @example Vintage Timepiece
             * @example Premium Selection
             */
            subtitle?: string | null;
            /**
             * Score
             * @description Market score from 0-100. Higher scores indicate better investment potential.
             * @example 87
             * @example 72
             * @example 65
             */
            score?: number | null;
            /**
             * @description Current market trend direction. 'up' indicates positive momentum, 'down' indicates negative momentum.
             * @example up
             * @example down
             */
            trend?: components["schemas"]["Trend"] | null;
            /**
             * Category Alias
             * @description Category this vignette belongs to, only for Marché spot
             * @example Marché de l'Art
             * @example Bijoux de Luxe
             */
            category_alias?: string | null;
            /**
             * @description Plan for this vignette
             * @example oracle
             * @example discover
             * @example intelligence
             */
            plan: components["schemas"]["Plan"];
            /**
             * Media Type
             * @description Media type of the vignette content
             * @example image
             * @example audio
             * @example pdf
             */
            media_type: string;
            /**
             * Pdf Url
             * @description More like a path than an url
             * @example GUIDE/jordan.pdf
             */
            pdf_url?: string | null;
            /**
             * Audio Url
             * @description More like a path than an url
             * @example PODCASt/jordan.mp3
             */
            audio_url?: string | null;
            /**
             * Id
             * @description Unique identifier of the vignette
             * @example vacherin
             * @example art
             * @example melon
             */
            id?: string | null;
            /**
             * Primary Country
             * @description Primary country associated with this vignette
             * @example France
             * @example United States
             * @example Switzerland
             */
            primary_country?: string | null;
        };
        /**
         * VignetteResponse
         * @description Response containing a list of vignettes for a category.
         *
         *     Used by the GET /vignettes endpoint to return all vignettes
         *     matching the requested category.
         * @example {
         *       "vignettes": [
         *         {
         *           "brand_name": "Nike Air Jordan",
         *           "category": "SNEAKERS",
         *           "public_url": "https://storage.example.com/vignettes/jordan.png",
         *           "score": 87,
         *           "subtitle": "Limited Edition Collection",
         *           "trend": "up"
         *         },
         *         {
         *           "brand_name": "Adidas Yeezy",
         *           "category": "SNEAKERS",
         *           "public_url": "https://storage.example.com/vignettes/yeezy.png",
         *           "score": 72,
         *           "subtitle": "Exclusive Release",
         *           "trend": "down"
         *         }
         *       ]
         *     }
         */
        VignetteResponse: {
            /**
             * Vignettes
             * @description List of vignettes for the requested category
             */
            vignettes: components["schemas"]["VignetteData"][];
        };
        /**
         * Vignettes
         * @description Vignette categories for luxury collectibles and investments.
         *
         *     Each category represents a different asset class with market insights and analysis.
         * @enum {string}
         */
        Vignettes: "ART" | "ART_CONTEMPORAIN" | "ART_TRADING_VALUE" | "BIJOUX" | "CARDS_US" | "CARS" | "CASH_FLOW_LEASING" | "CLASSIQUES" | "EMERGENTS" | "FIGURATIF" | "IMMO_LUXE" | "MARCHE_SPOT" | "MODERNES" | "MONTRES_LUXE" | "POP_ART" | "POST-WAR" | "SACS" | "SNEAKERS" | "STREET_ART" | "SURREALISME" | "WHISKY" | "WINE" | "REVELATIONS";
        /**
         * WithSubCatMarkdownCategory
         * @description Categories for tiers-dependent markdown content.
         * @enum {string}
         */
        WithSubCatMarkdownCategory: "RANKING" | "FLASH_INVEST";
        /**
         * WithoutSubCatMarkdownCategory
         * @description Categories for tiers-dependent markdown content.
         * @enum {string}
         */
        WithoutSubCatMarkdownCategory: "PORTFOLIO" | "CASH_FLOW_LEASING";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    langchain_agent_query_endpoint_langchain_agent_query_post: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LangChainAgentRequest"];
            };
        };
        responses: {
            /** @description SSE stream with JSON events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": string;
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    langchain_agent_info_endpoint_langchain_agent_info_get: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    langchain_agent_stream_test_endpoint_langchain_agent_stream_test_post: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    clear_cache_endpoint_test_clear_cache_post: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_tiers_independant_markdown_markdown_tiers_independant_get: {
        parameters: {
            query: {
                /** @description Name of the markdown file (without .md extension). URL-encode special characters. */
                markdown_name: string;
                /** @description Category to filter the vignette lookup in the database. */
                category?: components["schemas"]["Vignettes"] | null;
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream with markdown and optional product events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Markdown file not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Markdown file not found: overview.md"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_tiers_dependant_markdown_without_subcategory_markdown_tiers_dependant_without_sub_category_get: {
        parameters: {
            query: {
                /** @description Tier level for the content */
                tiers_level: components["schemas"]["TiersLevel"];
                /** @description Category of the markdown content */
                category: components["schemas"]["WithoutSubCatMarkdownCategory"];
                /** @description Name of the markdown file (without .md extension). URL-encode special characters. */
                markdown_name: string;
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Markdown content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "text": "# Portfolio Strategy\\n\\n## Overview\\n\\n..."
                     *     }
                     */
                    "application/json": components["schemas"]["MarkdownResponse"];
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Markdown file not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Markdown file not found: strategy.md"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_tiers_dependant_markdown_with_subcategory_markdown_tiers_dependant_with_sub_category_get: {
        parameters: {
            query: {
                /** @description Tier level for the content */
                tiers_level: components["schemas"]["TiersLevel"];
                /** @description Category of the markdown content */
                category: components["schemas"]["WithSubCatMarkdownCategory"];
                /** @description Sub-category (flash card type) to pick a random markdown from */
                sub_category: components["schemas"]["FlashCard"];
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Random markdown content from the folder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "text": "# Sneaker Investment Guide\\n\\n## Overview\\n\\n..."
                     *     }
                     */
                    "application/json": components["schemas"]["MarkdownResponse"];
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description No markdown files found in folder */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "No markdown files found in folder: DISCOVER/FLASH_INVEST/sneakers"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_vignettes_vignettes_get: {
        parameters: {
            query: {
                /** @description Vignette category to filter by */
                category: components["schemas"]["Vignettes"];
                /** @description Filter by main vignettes only */
                is_main?: boolean | null;
                /** @description Filter by art vignettes only */
                is_art?: boolean | null;
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of vignettes for the category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "vignettes": [
                     *         {
                     *           "category": "SNEAKERS",
                     *           "brand_name": "Nike Air Jordan",
                     *           "public_url": "https://storage.example.com/vignettes/jordan.png",
                     *           "subtitle": "Limited Edition Collection",
                     *           "score": 87,
                     *           "trend": "up",
                     *           "plan": "discover"
                     *         },
                     *         {
                     *           "category": "SNEAKERS",
                     *           "brand_name": "Adidas Yeezy",
                     *           "public_url": "https://storage.example.com/vignettes/yeezy.png",
                     *           "subtitle": "Exclusive Release",
                     *           "score": 72,
                     *           "trend": "down",
                     *           "plan": "intelligence"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["VignetteResponse"];
                };
            };
            /** @description Bad Request: The request cannot be processed due to an issue with the input. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Unsupported file type"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized: Authentication failed with Supabase. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid authentication credentials"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description No vignettes found for the specified category */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "No vignettes found for category: SNEAKERS"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable: Supabase server error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Supabase service is temporarily unavailable"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
}
